const numSetLen = 16;


const gameNameArray = [
    ["PAC MAN", "//cdn.jsdelivr.net/gh/omssp/nesscraper/local-roms/Pac-Man.nes.txt", "//cdn.jsdelivr.net/gh/omssp/nesscraper/images/pic01.jpg"],
    ["Super Mario Bros.", "//cdn.jsdelivr.net/gh/omssp/nesscraper/local-roms/Mario.nes.txt", "//cdn.jsdelivr.net/gh/omssp/nesscraper/images/pic02.jpg"],
    ["Dr. Mario", "//cdn.jsdelivr.net/gh/omssp/nesscraper/local-roms/Dr.Mario.nes.txt", "//cdn.jsdelivr.net/gh/omssp/nesscraper/images/pic03.jpg"],
    ["Contra", "//cdn.jsdelivr.net/gh/omssp/nesscraper/local-roms/Contra.nes.txt", "//cdn.jsdelivr.net/gh/omssp/nesscraper/images/pic04.jpg"],
    ["Donkey Kong", "//cdn.jsdelivr.net/gh/omssp/nesscraper/local-roms/DonkeyKong.nes.txt", "//cdn.jsdelivr.net/gh/omssp/nesscraper/images/pic06.jpg"],
    ["Tetris 2", "//cdn.jsdelivr.net/gh/omssp/nesscraper/local-roms/Tetris2.nes.txt", "//cdn.jsdelivr.net/gh/omssp/nesscraper/images/pic05.jpg"],
    ["Tennis", "//cdn.jsdelivr.net/gh/omssp/nesscraper/local-roms/Tennis.nes.txt", "//cdn.jsdelivr.net/gh/omssp/nesscraper/images/pic08.jpg"],
    ["Life Force", "//cdn.jsdelivr.net/gh/omssp/nesscraper/local-roms/LifeForce.nes.txt", "//cdn.jsdelivr.net/gh/omssp/nesscraper/images/pic07.jpg"],
    ["Mega Man", "//cdn.jsdelivr.net/gh/omssp/nesscraper/local-roms/MegaMan.nes.txt", "//cdn.jsdelivr.net/gh/omssp/nesscraper/images/pic09.jpg"],
    ["Bubble Bobble", "//cdn.jsdelivr.net/gh/omssp/nesscraper/local-roms/BubbleBobble.nes.txt", "//cdn.jsdelivr.net/gh/omssp/nesscraper/images/pic10.jpg"],
    ["The Legend of Zelda", "//cdn.jsdelivr.net/gh/omssp/nesscraper/local-roms/Zelda.nes.txt", "//cdn.jsdelivr.net/gh/omssp/nesscraper/images/pic11.jpg"],
    ["Ninja Gaiden", "//cdn.jsdelivr.net/gh/omssp/nesscraper/local-roms/NinjaGaiden.nes.txt", "//cdn.jsdelivr.net/gh/omssp/nesscraper/images/pic12.jpg"],
    ["Tetris", "//cdn.jsdelivr.net/gh/omssp/nesscraper/local-roms/Tetris.nes.txt", "//cdn.jsdelivr.net/gh/omssp/nesscraper/images/pic13.jpg"],
    ["Zelda II - The Adventure of Link", "//cdn.jsdelivr.net/gh/omssp/nesscraper/local-roms/ZeldaII.nes.txt", "//cdn.jsdelivr.net/gh/omssp/nesscraper/images/pic14.jpg"],
    ["Lemmings", "//cdn.jsdelivr.net/gh/omssp/nesscraper/local-roms/Lemmings.nes.txt", "//cdn.jsdelivr.net/gh/omssp/nesscraper/images/pic15.jpg"],
    ["Golf", "//cdn.jsdelivr.net/gh/omssp/nesscraper/local-roms/Golf.nes.txt", "//cdn.jsdelivr.net/gh/omssp/nesscraper/images/pic16.jpg"],
    ["Mappy", "//cdn.jsdelivr.net/gh/omssp/nesscraper/local-roms/Mappy.nes.txt", "//cdn.jsdelivr.net/gh/omssp/nesscraper/images/pic17.jpg"],
    ["Bomberman", "//cdn.jsdelivr.net/gh/omssp/nesscraper/local-roms/Bomberman.nes.txt", "//cdn.jsdelivr.net/gh/omssp/nesscraper/images/pic18.jpg"],
    ["Galaga", "//cdn.jsdelivr.net/gh/omssp/nesscraper/local-roms/Galaga.nes.txt", "//cdn.jsdelivr.net/gh/omssp/nesscraper/images/pic19.jpg"],
    ["Kung Fu", "//cdn.jsdelivr.net/gh/omssp/nesscraper/local-roms/KungFu.nes.txt", "//cdn.jsdelivr.net/gh/omssp/nesscraper/images/pic20.jpg"],
    ["Tiny Toon Adventures 2 - Trouble in Wackyland", "//cdn.jsdelivr.net/gh/omssp/nesscraper/local-roms/TinyToon2.nes.txt", "//cdn.jsdelivr.net/gh/omssp/nesscraper/images/pic22.jpg"],
    ["Tiny Toon Adventures", "//cdn.jsdelivr.net/gh/omssp/nesscraper/local-roms/TinyToon.nes.txt", "//cdn.jsdelivr.net/gh/omssp/nesscraper/images/pic21.jpg"],
    ["Popeye", "//cdn.jsdelivr.net/gh/omssp/nesscraper/local-roms/Popeye.nes.txt", "//cdn.jsdelivr.net/gh/omssp/nesscraper/images/pic24.jpg"],
    ["Mortal Kombat 4", "//cdn.jsdelivr.net/gh/omssp/nesscraper/local-roms/MK4.nes.txt", "//cdn.jsdelivr.net/gh/omssp/nesscraper/images/pic23.jpg"],
    ["Super Mario Kart Rider", "//cdn.jsdelivr.net/gh/omssp/nesscraper/local-roms/MarioKart.nes.txt", "//cdn.jsdelivr.net/gh/omssp/nesscraper/images/pic25.jpg"],
    ["Super Mario Bros. 3", "//cdn.jsdelivr.net/gh/omssp/nesscraper/local-roms/Mario3.nes.txt", "//cdn.jsdelivr.net/gh/omssp/nesscraper/images/pic26.jpg"],
    ["Tecmo Super Bowl", "//cdn.jsdelivr.net/gh/omssp/nesscraper/local-roms/Bowl.nes.txt", "//cdn.jsdelivr.net/gh/omssp/nesscraper/images/pic27.jpg"],
    ["Super Tank (Battle City Pirate)", "//cdn.jsdelivr.net/gh/omssp/nesscraper/downloads/67-battle-city-423.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/images/pic28.jpg"],
    ["Super Mario Bros. 2", "//cdn.jsdelivr.net/gh/omssp/nesscraper/local-roms/Mario2.nes.txt", "//cdn.jsdelivr.net/gh/omssp/nesscraper/images/pic29.jpg"],
    ["Final Fantasy", "//cdn.jsdelivr.net/gh/omssp/nesscraper/local-roms/Fantasy.nes.txt", "//cdn.jsdelivr.net/gh/omssp/nesscraper/images/pic30.jpg"],
    ["The Punisher", "//cdn.jsdelivr.net/gh/omssp/nesscraper/local-roms/Punisher.nes.txt", "//cdn.jsdelivr.net/gh/omssp/nesscraper/images/pic31.jpg"],
    ["Skate or Die!", "//cdn.jsdelivr.net/gh/omssp/nesscraper/local-roms/Skate.nes.txt", "//cdn.jsdelivr.net/gh/omssp/nesscraper/images/pic32.jpg"],
    ["Metroid", "//cdn.jsdelivr.net/gh/omssp/nesscraper/local-roms/Metroid.nes.txt", "//cdn.jsdelivr.net/gh/omssp/nesscraper/images/pic33.jpg"],
    ["Kirbys Adventure", "//cdn.jsdelivr.net/gh/omssp/nesscraper/local-roms/Kirby.nes.txt", "//cdn.jsdelivr.net/gh/omssp/nesscraper/images/pic34.jpg"],
    ["The Simpsons - Bart Vs the Space Mutants", "//cdn.jsdelivr.net/gh/omssp/nesscraper/local-roms/Simpsons.nes.txt", "//cdn.jsdelivr.net/gh/omssp/nesscraper/images/pic35.jpg"],
    ["Mega Man 2", "//cdn.jsdelivr.net/gh/omssp/nesscraper/local-roms/MegaMan2.nes.txt", "//cdn.jsdelivr.net/gh/omssp/nesscraper/images/pic36.jpg"],
    ["Mega Man 3", "//cdn.jsdelivr.net/gh/omssp/nesscraper/local-roms/MegaMan3.nes.txt", "//cdn.jsdelivr.net/gh/omssp/nesscraper/images/pic38.jpg"],
    ["Ice Climber", "//cdn.jsdelivr.net/gh/omssp/nesscraper/local-roms/IceClimber.nes.txt", "//cdn.jsdelivr.net/gh/omssp/nesscraper/images/pic37.jpg"],
    ["Mega Man 4", "//cdn.jsdelivr.net/gh/omssp/nesscraper/local-roms/MegaMan4.nes.txt", "//cdn.jsdelivr.net/gh/omssp/nesscraper/images/pic40.jpg"],
    ["Castlevania 2 - Simon's Quest", "//cdn.jsdelivr.net/gh/omssp/nesscraper/local-roms/Castlevania2.nes.txt", "//cdn.jsdelivr.net/gh/omssp/nesscraper/images/pic39.jpg"],
    ["Castlevania", "//cdn.jsdelivr.net/gh/omssp/nesscraper/local-roms/Castlevania.nes.txt", "//cdn.jsdelivr.net/gh/omssp/nesscraper/images/pic41.jpg"],
    ["Mega Man 5", "//cdn.jsdelivr.net/gh/omssp/nesscraper/local-roms/MegaMan5.nes.txt", "//cdn.jsdelivr.net/gh/omssp/nesscraper/images/pic42.jpg"],
    ["Chip n Dale Rescue Rangers", "//cdn.jsdelivr.net/gh/omssp/nesscraper/local-roms/ChipnDale.nes.txt", "//cdn.jsdelivr.net/gh/omssp/nesscraper/images/pic43.jpg"],
    ["Mega Man 6", "//cdn.jsdelivr.net/gh/omssp/nesscraper/local-roms/MegaMan6.nes.txt", "//cdn.jsdelivr.net/gh/omssp/nesscraper/images/pic44.jpg"],
    ["Duck Tales", "//cdn.jsdelivr.net/gh/omssp/nesscraper/local-roms/DuckTales.nes.txt", "//cdn.jsdelivr.net/gh/omssp/nesscraper/images/pic45.jpg"],
    ["Battletoads", "//cdn.jsdelivr.net/gh/omssp/nesscraper/local-roms/Battletoads.nes.txt", "//cdn.jsdelivr.net/gh/omssp/nesscraper/images/pic46.jpg"],
    ["Duck Tales 2", "//cdn.jsdelivr.net/gh/omssp/nesscraper/local-roms/DuckTales2.nes.txt", "//cdn.jsdelivr.net/gh/omssp/nesscraper/images/pic47.jpg"],
    ["Excitebike", "//cdn.jsdelivr.net/gh/omssp/nesscraper/local-roms/Excitebike.nes.txt", "//cdn.jsdelivr.net/gh/omssp/nesscraper/images/pic48.jpg"],
    ["Rambo", "//cdn.jsdelivr.net/gh/omssp/nesscraper/local-roms/Rambo.nes.txt", "//cdn.jsdelivr.net/gh/omssp/nesscraper/images/pic49.jpg"],
    ["Ninja Gaiden 2 - The Dark Sword of Chaos", "//cdn.jsdelivr.net/gh/omssp/nesscraper/local-roms/NinjaGaiden2.nes.txt", "//cdn.jsdelivr.net/gh/omssp/nesscraper/images/pic50.jpg"],
    ["Prince of Persia", "//cdn.jsdelivr.net/gh/omssp/nesscraper/local-roms/PoP.nes.txt", "//cdn.jsdelivr.net/gh/omssp/nesscraper/images/pic51.jpg"],
    ["Ninja Gaiden 3 - The Ancient Ship of Doom", "//cdn.jsdelivr.net/gh/omssp/nesscraper/local-roms/NinjaGaiden3.nes.txt", "//cdn.jsdelivr.net/gh/omssp/nesscraper/images/pic52.jpg"],
    ["Tom & Jerry (and Tuffy)", "//cdn.jsdelivr.net/gh/omssp/nesscraper/local-roms/TomJerry.nes.txt", "//cdn.jsdelivr.net/gh/omssp/nesscraper/images/pic54.jpg"],
    ["Snow Brothers", "//cdn.jsdelivr.net/gh/omssp/nesscraper/local-roms/SnowBros.nes.txt", "//cdn.jsdelivr.net/gh/omssp/nesscraper/images/pic53.jpg"],
    ["Teenage Mutant Ninja Turtles", "//cdn.jsdelivr.net/gh/omssp/nesscraper/local-roms/TMNT.nes.txt", "//cdn.jsdelivr.net/gh/omssp/nesscraper/images/pic56.jpg"],
    ["Hudsons Adventure Island 3", "//cdn.jsdelivr.net/gh/omssp/nesscraper/local-roms/AIsland3.nes.txt", "//cdn.jsdelivr.net/gh/omssp/nesscraper/images/pic55.jpg"],
    ["Ghosts n Goblins", "//cdn.jsdelivr.net/gh/omssp/nesscraper/local-roms/GhostsGoblins.nes.txt", "//cdn.jsdelivr.net/gh/omssp/nesscraper/images/pic57.jpg"],
    ["Teenage Mutant Ninja Turtles 2", "//cdn.jsdelivr.net/gh/omssp/nesscraper/local-roms/TMNT2.nes.txt", "//cdn.jsdelivr.net/gh/omssp/nesscraper/images/pic58.jpg"],
    ["Hudson's Adventure Island II", "//cdn.jsdelivr.net/gh/omssp/nesscraper/local-roms/AIsland2.nes.txt", "//cdn.jsdelivr.net/gh/omssp/nesscraper/images/pic59.jpg"],
    ["Batman", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/58-batman.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/58-batman.jpg"],
    ["Mighty Final Fight", "//cdn.jsdelivr.net/gh/omssp/nesscraper/local-roms/MightyFF.nes.txt", "//cdn.jsdelivr.net/gh/omssp/nesscraper/images/pic61.jpg"],
    ["Double Dragon 3 - The Sacred Stones", "//cdn.jsdelivr.net/gh/omssp/nesscraper/local-roms/DoubleDragon3.nes.txt", "//cdn.jsdelivr.net/gh/omssp/nesscraper/images/pic62.jpg"],
    ["Metal Gear", "//cdn.jsdelivr.net/gh/omssp/nesscraper/local-roms/MetalGear.nes.txt", "//cdn.jsdelivr.net/gh/omssp/nesscraper/images/pic63.jpg"],
    ["F-1 Race", "//cdn.jsdelivr.net/gh/omssp/nesscraper/local-roms/F1Race.nes.txt", "//cdn.jsdelivr.net/gh/omssp/nesscraper/images/pic64.jpg"],
    ["Adventures of Lolo 3", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/17-adventures-of-lolo-3.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/17-adventures-of-lolo-3.jpg"],
    ["Astyanax", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/36-astyanax.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/36-astyanax.jpg"],
    ["Bionic Commando", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/72-bionic-commando.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/72-bionic-commando.jpg"],
    ["Blaster Master", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/75-blaster-master.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/75-blaster-master.jpg"],
    ["Crystalis", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/127-crystalis.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/127-crystalis.jpg"],
    ["Dragon Warrior III", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/161-dragon-warrior-iii.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/161-dragon-warrior-iii.jpg"],
    ["Gradius", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/208-gradius.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/208-gradius.jpg"],
    ["Ikari Warriors II - Victory Road", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/229-ikari-warriors-ii-victory-road.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/229-ikari-warriors-ii-victory-road.jpg"],
    ["Ironsword - Wizards & Warriors II", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/237-ironsword-wizards-warriors-ii.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/237-ironsword-wizards-warriors-ii.jpg"],
    ["Jackal", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/240-jackal.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/240-jackal.jpg"],
    ["Journey to Silius", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/248-journey-to-silius.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/248-journey-to-silius.jpg"],
    ["Kickle Cubicle", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/258-kickle-cubicle.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/258-kickle-cubicle.jpg"],
    ["Legendary Wings", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/282-legendary-wings.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/282-legendary-wings.jpg"],
    ["Little Samson", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/290-little-samson.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/290-little-samson.jpg"],
    ["Maniac Mansion", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/299-maniac-mansion.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/299-maniac-mansion.jpg"],
    ["Mickey Mousecapade", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/315-mickey-mousecapade.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/315-mickey-mousecapade.jpg"],
    ["Qix", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/371-qix.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/371-qix.jpg"],
    ["Rad Racer 2", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/376-rad-racer-2.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/376-rad-racer-2.jpg"],
    ["River City Ransom", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/387-river-city-ransom.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/387-river-city-ransom.jpg"],
    ["Shadowgate", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/403-shadowgate.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/403-shadowgate.jpg"],
    ["Startropics", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/436-startropics.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/436-startropics.jpg"],
    ["Stinger", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/437-stinger.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/437-stinger.jpg"],
    ["Super C", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/442-super-c.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/442-super-c.jpg"],
    ["Willow", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/520-willow.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/520-willow.jpg"],
    ["Wizards & Warriors III - Kuros - Visions of Power", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/523-wizards-warriors-iii-kuros-visions-of-power.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/523-wizards-warriors-iii-kuros-visions-of-power.jpg"],
    ["Zombie Nation", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/542-zombie-nation.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/542-zombie-nation.jpg"],
    ["1943 - The Battle of Midway", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/1-1943-the-battle-of-midway.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/1-1943-the-battle-of-midway.jpg"],
    ["3-D Battles of World Runner", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/2-3-d-battles-of-world-runner.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/2-3-d-battles-of-world-runner.jpg"],
    ["8 Eyes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/4-8-eyes.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/4-8-eyes.jpg"],
    ["Abadox - The Deadly Inner War", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/5-abadox-the-deadly-inner-war.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/5-abadox-the-deadly-inner-war.jpg"],
    ["Advanced Dungeons & Dragons - Dragon Strike", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/7-advanced-dungeons-dragons-dragon-strike.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/7-advanced-dungeons-dragons-dragon-strike.jpg"],
    ["Advanced Dungeons & Dragons - Heroes of the Lance", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/8-advanced-dungeons-dragons-heroes-of-the-lance.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/8-advanced-dungeons-dragons-heroes-of-the-lance.jpg"],
    ["Advanced Dungeons & Dragons - Hillsfar", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/9-advanced-dungeons-dragons-hillsfar.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/9-advanced-dungeons-dragons-hillsfar.jpg"],
    ["Advanced Dungeons & Dragons - Pool of Radiance", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/10-advanced-dungeons-dragons-pool-of-radiance.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/10-advanced-dungeons-dragons-pool-of-radiance.jpg"],
    ["Adventures in the Magic Kingdom", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/11-adventures-in-the-magic-kingdom.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/11-adventures-in-the-magic-kingdom.jpg"],
    ["Adventures of Bayou Billy", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/12-adventures-of-bayou-billy.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/12-adventures-of-bayou-billy.jpg"],
    ["Adventures of Dino Riki", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/13-adventures-of-dino-riki.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/13-adventures-of-dino-riki.jpg"],
    ["Adventures of Gilligan's Island", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/14-adventures-of-gilligan-s-island.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/14-adventures-of-gilligan-s-island.jpg"],
    ["Adventures of Lolo", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/15-adventures-of-lolo.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/15-adventures-of-lolo.jpg"],
    ["Adventures of Lolo 2", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/16-adventures-of-lolo-2.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/16-adventures-of-lolo-2.jpg"],
    ["Adventures of Tom Sawyer", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/19-adventures-of-tom-sawyer.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/19-adventures-of-tom-sawyer.jpg"],
    ["Air Fortress", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/20-air-fortress.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/20-air-fortress.jpg"],
    ["Airwolf", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/21-airwolf.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/21-airwolf.jpg"],
    ["Al Unser Jr", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/22-al-unser-jr.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/22-al-unser-jr.jpg"],
    ["Aladdin", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/23-aladdin.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/23-aladdin.jpg"],
    ["Alfred Chicken", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/24-alfred-chicken.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/24-alfred-chicken.jpg"],
    ["Alien 3", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/25-alien-3.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/25-alien-3.jpg"],
    ["All-Pro Basketball", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/26-all-pro-basketball.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/26-all-pro-basketball.jpg"],
    ["Amagon", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/28-amagon.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/28-amagon.jpg"],
    ["American Gladiators", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/29-american-gladiators.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/29-american-gladiators.jpg"],
    ["Anticipation", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/30-anticipation.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/30-anticipation.jpg"],
    ["Arch Rivals - A Basketbrawl", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/31-arch-rivals-a-basketbrawl.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/31-arch-rivals-a-basketbrawl.jpg"],
    ["Archon", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/32-archon.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/32-archon.jpg"],
    ["Asterix", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/35-asterix.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/35-asterix.jpg"],
    ["Athena", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/37-athena.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/37-athena.jpg"],
    ["Attack of the Killer Tomatoes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/39-attack-of-the-killer-tomatoes.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/39-attack-of-the-killer-tomatoes.jpg"],
    ["Aussie Rules Footy", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/40-aussie-rules-footy.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/40-aussie-rules-footy.jpg"],
    ["Back to the Future", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/41-back-to-the-future.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/41-back-to-the-future.jpg"],
    ["Back to the Future Part II & III", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/42-back-to-the-future-part-ii-iii.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/42-back-to-the-future-part-ii-iii.jpg"],
    ["Bad Dudes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/43-bad-dudes.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/43-bad-dudes.jpg"],
    ["Balloon Fight", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/46-balloon-fight.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/46-balloon-fight.jpg"],
    ["Bandit Kings of Ancient China", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/48-bandit-kings-of-ancient-china.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/48-bandit-kings-of-ancient-china.jpg"],
    ["Bases Loaded II", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/57-bases-loaded-ii.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/57-bases-loaded-ii.jpg"],
    ["Batman - Return of the Joker", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/59-batman-return-of-the-joker.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/59-batman-return-of-the-joker.jpg"],
    ["Batman Returns", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/60-batman-returns.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/60-batman-returns.jpg"],
    ["Battle of Olympus", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/62-battle-of-olympus.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/62-battle-of-olympus.jpg"],
    ["Battle Tank", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/63-battle-tank.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/63-battle-tank.jpg"],
    ["Battletoads & Double Dragon - The Ultimate Team", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/65-battletoads-double-dragon-the-ultimate-team.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/65-battletoads-double-dragon-the-ultimate-team.jpg"],
    ["Beauty and the Beast", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/67-beauty-and-the-beast.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/67-beauty-and-the-beast.jpg"],
    ["Beetlejuice", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/68-beetlejuice.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/68-beetlejuice.jpg"],
    ["Black Bass USA", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/73-black-bass-usa.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/73-black-bass-usa.jpg"],
    ["Blue Marlin", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/76-blue-marlin.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/76-blue-marlin.jpg"],
    ["Blues Brothers", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/77-blues-brothers.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/77-blues-brothers.jpg"],
    ["Bomberman II", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/79-bomberman-ii.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/79-bomberman-ii.jpg"],
    ["Bonk's Adventure", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/80-bonk-s-adventure.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/80-bonk-s-adventure.jpg"],
    ["Boulder Dash", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/81-boulder-dash.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/81-boulder-dash.jpg"],
    ["Bram Stoker's Dracula", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/82-bram-stoker-s-dracula.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/82-bram-stoker-s-dracula.jpg"],
    ["BreakThru", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/83-breakthru.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/83-breakthru.jpg"],
    ["Bucky O Hare", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/86-bucky-o-hare.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/86-bucky-o-hare.jpg"],
    ["Bugs Bunny Birthday Blowout", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/87-bugs-bunny-birthday-blowout.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/87-bugs-bunny-birthday-blowout.jpg"],
    ["Bugs Bunny Crazy Castle", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/88-bugs-bunny-crazy-castle.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/88-bugs-bunny-crazy-castle.jpg"],
    ["Burai Fighter", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/90-burai-fighter.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/90-burai-fighter.jpg"],
    ["Action 52", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/91-action-52.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/91-action-52.jpg"],
    ["Captain Planet and The Planeteers", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/95-captain-planet-and-the-planeteers.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/95-captain-planet-and-the-planeteers.jpg"],
    ["Casino Kid", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/96-casino-kid.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/96-casino-kid.jpg"],
    ["Castelian", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/97-castelian.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/97-castelian.jpg"],
    ["Castlevania III - Dracula's Curse", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/102-castlevania-iii-dracula-s-curse.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/102-castlevania-iii-dracula-s-curse.jpg"],
    ["Championship Bowling", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/104-championship-bowling.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/104-championship-bowling.jpg"],
    ["Championship Rally", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/105-championship-rally.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/105-championship-rally.jpg"],
    ["Circus Charlie", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/110-circus-charlie.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/110-circus-charlie.jpg"],
    ["City Connection", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/111-city-connection.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/111-city-connection.jpg"],
    ["Classic Concentration", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/112-classic-concentration.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/112-classic-concentration.jpg"],
    ["Cliffhanger", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/113-cliffhanger.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/113-cliffhanger.jpg"],
    ["Cobra Command", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/114-cobra-command.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/114-cobra-command.jpg"],
    ["Code Name - Viper", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/116-code-name-viper.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/116-code-name-viper.jpg"],
    ["Color A Dinosaur", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/117-color-a-dinosaur.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/117-color-a-dinosaur.jpg"],
    ["Commando", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/118-commando.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/118-commando.jpg"],
    ["Conflict", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/119-conflict.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/119-conflict.jpg"],
    ["Conquest of the Crystal Palace", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/120-conquest-of-the-crystal-palace.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/120-conquest-of-the-crystal-palace.jpg"],
    ["Contra Force", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/122-contra-force.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/122-contra-force.jpg"],
    ["Cowboy Kid", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/124-cowboy-kid.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/124-cowboy-kid.jpg"],
    ["Cyberball", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/128-cyberball.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/128-cyberball.jpg"],
    ["Cybernoid - The Fighting Machine", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/129-cybernoid-the-fighting-machine.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/129-cybernoid-the-fighting-machine.jpg"],
    ["Dance Aerobics", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/130-dance-aerobics.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/130-dance-aerobics.jpg"],
    ["Darkwing Duck", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/133-darkwing-duck.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/133-darkwing-duck.jpg"],
    ["Day Dreamin  Davey", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/135-day-dreamin-davey.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/135-day-dreamin-davey.jpg"],
    ["Deadly Towers", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/137-deadly-towers.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/137-deadly-towers.jpg"],
    ["Defender of the Crown", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/139-defender-of-the-crown.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/139-defender-of-the-crown.jpg"],
    ["Defenders of Dynatron City", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/140-defenders-of-dynatron-city.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/140-defenders-of-dynatron-city.jpg"],
    ["Deja Vu", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/141-deja-vu.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/141-deja-vu.jpg"],
    ["Desert Commander", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/143-desert-commander.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/143-desert-commander.jpg"],
    ["Die Hard", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/147-die-hard.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/147-die-hard.jpg"],
    ["Digger - The Legend of the Lost City", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/149-digger-the-legend-of-the-lost-city.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/149-digger-the-legend-of-the-lost-city.jpg"],
    ["Donkey Kong 3", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/150-donkey-kong-3.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/150-donkey-kong-3.jpg"],
    ["Donkey Kong Classics", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/151-donkey-kong-classics.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/151-donkey-kong-classics.jpg"],
    ["Donkey Kong Jr", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/152-donkey-kong-jr.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/152-donkey-kong-jr.jpg"],
    ["Double Dragon", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/153-double-dragon.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/153-double-dragon.jpg"],
    ["Dr", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/155-dr.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/155-dr.jpg"],
    ["Dragon Power", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/157-dragon-power.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/157-dragon-power.jpg"],
    ["Dragon's Lair", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/158-dragon-s-lair.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/158-dragon-s-lair.jpg"],
    ["Dragon Warrior II", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/160-dragon-warrior-ii.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/160-dragon-warrior-ii.jpg"],
    ["Dragon Warrior IV", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/162-dragon-warrior-iv.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/162-dragon-warrior-iv.jpg"],
    ["Dungeon Magic - Sword of the Elements", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/165-dungeon-magic-sword-of-the-elements.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/165-dungeon-magic-sword-of-the-elements.jpg"],
    ["Dusty Diamond's All-Star Softball", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/166-dusty-diamond-s-all-star-softball.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/166-dusty-diamond-s-all-star-softball.jpg"],
    ["Dynowarz - The Destruction of Spondylus", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/167-dynowarz-the-destruction-of-spondylus.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/167-dynowarz-the-destruction-of-spondylus.jpg"],
    ["Elite", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/170-elite.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/170-elite.jpg"],
    ["F-15 Strike Eagle", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/173-f-15-strike-eagle.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/173-f-15-strike-eagle.jpg"],
    ["Family Feud", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/174-family-feud.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/174-family-feud.jpg"],
    ["Felix the Cat", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/176-felix-the-cat.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/176-felix-the-cat.jpg"],
    ["Fist of the North Star", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/182-fist-of-the-north-star.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/182-fist-of-the-north-star.jpg"],
    ["Flight of the Intruder", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/183-flight-of-the-intruder.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/183-flight-of-the-intruder.jpg"],
    ["Flying Dragon - The Secret Scroll", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/184-flying-dragon-the-secret-scroll.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/184-flying-dragon-the-secret-scroll.jpg"],
    ["Frankenstein - The Monster Returns", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/187-frankenstein-the-monster-returns.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/187-frankenstein-the-monster-returns.jpg"],
    ["Friday the 13th", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/189-friday-the-13th.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/189-friday-the-13th.jpg"],
    ["Fun House", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/190-fun-house.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/190-fun-house.jpg"],
    ["G", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/191-g.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/191-g.jpg"],
    ["Galaxy 5000", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/192-galaxy-5000.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/192-galaxy-5000.jpg"],
    ["Gauntlet", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/193-gauntlet.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/193-gauntlet.jpg"],
    ["Gauntlet II", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/194-gauntlet-ii.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/194-gauntlet-ii.jpg"],
    ["Ghostbusters", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/197-ghostbusters.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/197-ghostbusters.jpg"],
    ["Ghostbusters II", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/198-ghostbusters-ii.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/198-ghostbusters-ii.jpg"],
    ["Godzilla - Monster of Monsters", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/202-godzilla-monster-of-monsters.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/202-godzilla-monster-of-monsters.jpg"],
    ["Godzilla 2 - War of the Monsters", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/203-godzilla-2-war-of-the-monsters.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/203-godzilla-2-war-of-the-monsters.jpg"],
    ["Golgo 13 - Top Secret Episode", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/205-golgo-13-top-secret-episode.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/205-golgo-13-top-secret-episode.jpg"],
    ["Goonies II", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/206-goonies-ii.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/206-goonies-ii.jpg"],
    ["Guardian Legend", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/210-guardian-legend.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/210-guardian-legend.jpg"],
    ["Guerrilla War", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/211-guerrilla-war.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/211-guerrilla-war.jpg"],
    ["Gun-Nac", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/213-gun-nac.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/213-gun-nac.jpg"],
    ["Gun", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/214-gun.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/214-gun.jpg"],
    ["Gyruss", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/215-gyruss.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/215-gyruss.jpg"],
    ["Hatris", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/217-hatris.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/217-hatris.jpg"],
    ["Heavy Barrel", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/218-heavy-barrel.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/218-heavy-barrel.jpg"],
    ["Heavy Shreddin", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/219-heavy-shreddin.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/219-heavy-shreddin.jpg"],
    ["Home Alone 2 - Lost in New York", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/221-home-alone-2-lost-in-new-york.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/221-home-alone-2-lost-in-new-york.jpg"],
    ["Hudson's Adventure Island", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/224-hudson-s-adventure-island.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/224-hudson-s-adventure-island.jpg"],
    ["Hydlide", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/225-hydlide.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/225-hydlide.jpg"],
    ["Ikari III - The Rescue", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/228-ikari-iii-the-rescue.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/228-ikari-iii-the-rescue.jpg"],
    ["Image Fight", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/230-image-fight.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/230-image-fight.jpg"],
    ["Immortal", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/231-immortal.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/231-immortal.jpg"],
    ["Impossible Mission II", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/232-impossible-mission-ii.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/232-impossible-mission-ii.jpg"],
    ["Indiana Jones and the Last Crusade", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/234-indiana-jones-and-the-last-crusade.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/234-indiana-jones-and-the-last-crusade.jpg"],
    ["Isolated Warrior", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/238-isolated-warrior.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/238-isolated-warrior.jpg"],
    ["Ivan Ironman Stewart's Super Off-Road", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/239-ivan-ironman-stewart-s-super-off-road.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/239-ivan-ironman-stewart-s-super-off-road.jpg"],
    ["Jackie Chan's Action Kung Fu", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/241-jackie-chan-s-action-kung-fu.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/241-jackie-chan-s-action-kung-fu.jpg"],
    ["Jimmy Connor's Tennis", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/245-jimmy-connor-s-tennis.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/245-jimmy-connor-s-tennis.jpg"],
    ["Joe & Mac - Caveman Ninja", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/246-joe-mac-caveman-ninja.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/246-joe-mac-caveman-ninja.jpg"],
    ["John Elway's Quarterback", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/247-john-elway-s-quarterback.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/247-john-elway-s-quarterback.jpg"],
    ["Joust", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/249-joust.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/249-joust.jpg"],
    ["Jungle Book", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/250-jungle-book.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/250-jungle-book.jpg"],
    ["Jurassic Park", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/251-jurassic-park.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/251-jurassic-park.jpg"],
    ["Kabuki - Quantum Fighter", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/252-kabuki-quantum-fighter.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/252-kabuki-quantum-fighter.jpg"],
    ["Karate Champ", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/253-karate-champ.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/253-karate-champ.jpg"],
    ["Karate Kid", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/254-karate-kid.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/254-karate-kid.jpg"],
    ["Karnov", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/255-karnov.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/255-karnov.jpg"],
    ["Kick Master", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/256-kick-master.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/256-kick-master.jpg"],
    ["Kid Klown", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/259-kid-klown.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/259-kid-klown.jpg"],
    ["Kid Kool and the Quest for the 7 Wonder Herbs", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/260-kid-kool-and-the-quest-for-the-7-wonder-herbs.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/260-kid-kool-and-the-quest-for-the-7-wonder-herbs.jpg"],
    ["Konami Hyper Soccer", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/267-konami-hyper-soccer.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/267-konami-hyper-soccer.jpg"],
    ["Krusty's Fun House", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/269-krusty-s-fun-house.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/269-krusty-s-fun-house.jpg"],
    ["Kung-Fu Heroes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/271-kung-fu-heroes.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/271-kung-fu-heroes.jpg"],
    ["L Empereur", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/272-l-empereur.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/272-l-empereur.jpg"],
    ["Last Action Hero", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/273-last-action-hero.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/273-last-action-hero.jpg"],
    ["Last Ninja", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/274-last-ninja.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/274-last-ninja.jpg"],
    ["Lee Trevino's Fighting Golf", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/276-lee-trevino-s-fighting-golf.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/276-lee-trevino-s-fighting-golf.jpg"],
    ["Legend of Kage", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/278-legend-of-kage.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/278-legend-of-kage.jpg"],
    ["Legend of Prince Valiant", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/279-legend-of-prince-valiant.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/279-legend-of-prince-valiant.jpg"],
    ["Lion King", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/286-lion-king.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/286-lion-king.jpg"],
    ["Little Mermaid", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/287-little-mermaid.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/287-little-mermaid.jpg"],
    ["Little Nemo - The Dream Master", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/288-little-nemo-the-dream-master.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/288-little-nemo-the-dream-master.jpg"],
    ["Little Ninja Brothers", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/289-little-ninja-brothers.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/289-little-ninja-brothers.jpg"],
    ["Lone Ranger", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/292-lone-ranger.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/292-lone-ranger.jpg"],
    ["Low G Man - The Low Gravity Man", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/293-low-g-man-the-low-gravity-man.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/293-low-g-man-the-low-gravity-man.jpg"],
    ["Magic of Scheherazade", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/297-magic-of-scheherazade.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/297-magic-of-scheherazade.jpg"],
    ["Marble Madness", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/301-marble-madness.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/301-marble-madness.jpg"],
    ["Mario is Missing", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/304-mario-is-missing.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/304-mario-is-missing.jpg"],
    ["Mechanized Attack", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/306-mechanized-attack.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/306-mechanized-attack.jpg"],
    ["Megaman", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/307-megaman.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/307-megaman.jpg"],
    ["Megaman II", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/308-megaman-ii.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/308-megaman-ii.jpg"],
    ["Megaman III", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/309-megaman-iii.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/309-megaman-iii.jpg"],
    ["Megaman V", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/310-megaman-v.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/310-megaman-v.jpg"],
    ["Mission - Impossible", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/321-mission-impossible.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/321-mission-impossible.jpg"],
    ["Monopoly", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/322-monopoly.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/322-monopoly.jpg"],
    ["Monster Party", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/324-monster-party.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/324-monster-party.jpg"],
    ["Monster Truck Rally", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/325-monster-truck-rally.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/325-monster-truck-rally.jpg"],
    ["Mr", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/326-mr.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/326-mr.jpg"],
    ["Ms", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/327-ms.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/327-ms.jpg"],
    ["NES Open Tournament Golf", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/329-nes-open-tournament-golf.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/329-nes-open-tournament-golf.jpg"],
    ["New Ghostbusters II", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/331-new-ghostbusters-ii.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/331-new-ghostbusters-ii.jpg"],
    ["NFL Football", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/332-nfl-football.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/332-nfl-football.jpg"],
    ["Nightshade", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/334-nightshade.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/334-nightshade.jpg"],
    ["Ninja Crusaders", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/335-ninja-crusaders.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/335-ninja-crusaders.jpg"],
    ["Ninja Kid", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/339-ninja-kid.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/339-ninja-kid.jpg"],
    ["Nintendo World Championships 1990", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/340-nintendo-world-championships-1990.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/340-nintendo-world-championships-1990.jpg"],
    ["Nintendo World Cup", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/341-nintendo-world-cup.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/341-nintendo-world-cup.jpg"],
    ["Noah's Ark", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/342-noah-s-ark.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/342-noah-s-ark.jpg"],
    ["Nobunaga's Ambition", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/343-nobunaga-s-ambition.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/343-nobunaga-s-ambition.jpg"],
    ["Operation Wolf", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/345-operation-wolf.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/345-operation-wolf.jpg"],
    ["Overlord", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/348-overlord.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/348-overlord.jpg"],
    ["Yie Ar Kung Fu", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/322-yie-ar-kung-fu-629.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/322-yie-ar-kung-fu-629.jpg"],
    // ["Pac-Man", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/350-pac-man.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/350-pac-man.jpg"],
    ["Palamedes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/351-palamedes.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/351-palamedes.jpg"],
    ["Panic Restaurant", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/352-panic-restaurant.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/352-panic-restaurant.jpg"],
    ["Paperboy", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/353-paperboy.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/353-paperboy.jpg"],
    ["Paperboy 2", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/354-paperboy-2.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/354-paperboy-2.jpg"],
    ["Parodius", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/355-parodius.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/355-parodius.jpg"],
    ["Peter Pan & The Pirates", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/356-peter-pan-the-pirates.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/356-peter-pan-the-pirates.jpg"],
    ["Pinball Quest", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/359-pinball-quest.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/359-pinball-quest.jpg"],
    ["Pipe Dream", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/360-pipe-dream.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/360-pipe-dream.jpg"],
    ["Pirates", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/361-pirates.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/361-pirates.jpg"],
    ["Princess Tomato in Salad Kingdom", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/366-princess-tomato-in-salad-kingdom.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/366-princess-tomato-in-salad-kingdom.jpg"],
    ["Punch-Out", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/367-punch-out.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/367-punch-out.jpg"],
    ["Puzznic", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/369-puzznic.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/369-puzznic.jpg"],
    ["Race America", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/373-race-america.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/373-race-america.jpg"],
    ["Racket Attack", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/374-racket-attack.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/374-racket-attack.jpg"],
    ["Rainbow Islands - The Story of Bubble Bobble 2", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/378-rainbow-islands-the-story-of-bubble-bobble-2.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/378-rainbow-islands-the-story-of-bubble-bobble-2.jpg"],
    ["Rampage", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/380-rampage.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/380-rampage.jpg"],
    ["Rampart", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/381-rampart.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/381-rampart.jpg"],
    ["Ren & Stimpy Show", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/383-ren-stimpy-show.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/383-ren-stimpy-show.jpg"],
    ["Renegade", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/384-renegade.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/384-renegade.jpg"],
    ["Road Fighter", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/388-road-fighter.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/388-road-fighter.jpg"],
    ["RoadBlasters", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/389-roadblasters.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/389-roadblasters.jpg"],
    ["RoboCop", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/391-robocop.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/391-robocop.jpg"],
    ["RoboCop 3", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/392-robocop-3.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/392-robocop-3.jpg"],
    ["Rocket Ranger", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/393-rocket-ranger.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/393-rocket-ranger.jpg"],
    ["Rocketeer", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/394-rocketeer.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/394-rocketeer.jpg"],
    ["Rod Land", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/396-rod-land.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/396-rod-land.jpg"],
    ["Rollerball", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/397-rollerball.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/397-rollerball.jpg"],
    ["Rollergames", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/398-rollergames.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/398-rollergames.jpg"],
    ["Seicross", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/400-seicross.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/400-seicross.jpg"],
    ["Sesame Street ABC", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/401-sesame-street-abc.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/401-sesame-street-abc.jpg"],
    ["Shadow of the Ninja", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/402-shadow-of-the-ninja.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/402-shadow-of-the-ninja.jpg"],
    ["Shatterhand", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/404-shatterhand.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/404-shatterhand.jpg"],
    ["Side Pocket", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/405-side-pocket.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/405-side-pocket.jpg"],
    ["Slalom", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/411-slalom.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/411-slalom.jpg"],
    ["Smash T", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/412-smash-t.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/412-smash-t.jpg"],
    ["Snake Rattle N Roll", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/413-snake-rattle-n-roll.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/413-snake-rattle-n-roll.jpg"],
    ["Snake's Revenge", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/414-snake-s-revenge.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/414-snake-s-revenge.jpg"],
    ["Snoopy's Silly Sports Spectacular", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/415-snoopy-s-silly-sports-spectacular.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/415-snoopy-s-silly-sports-spectacular.jpg"],
    ["Solar Jetman - Hunt for the Golden Warpship", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/417-solar-jetman-hunt-for-the-golden-warpship.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/417-solar-jetman-hunt-for-the-golden-warpship.jpg"],
    ["Solomon's Key", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/418-solomon-s-key.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/418-solomon-s-key.jpg"],
    ["Solstice - The Quest for the Staff of Demnos", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/419-solstice-the-quest-for-the-staff-of-demnos.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/419-solstice-the-quest-for-the-staff-of-demnos.jpg"],
    ["Spider-Man - Return of the Sinister Six", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/422-spider-man-return-of-the-sinister-six.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/422-spider-man-return-of-the-sinister-six.jpg"],
    ["Spy Vs Spy", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/425-spy-vs-spy.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/425-spy-vs-spy.jpg"],
    ["Stadium Events", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/427-stadium-events.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/427-stadium-events.jpg"],
    ["Star Force", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/429-star-force.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/429-star-force.jpg"],
    ["Star Trek - 25th Anniversary", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/430-star-trek-25th-anniversary.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/430-star-trek-25th-anniversary.jpg"],
    ["Star Trek - The Next Generation", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/431-star-trek-the-next-generation.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/431-star-trek-the-next-generation.jpg"],
    ["Star Voyager", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/432-star-voyager.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/432-star-voyager.jpg"],
    ["Star Wars", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/433-star-wars.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/433-star-wars.jpg"],
    ["Star Wars - The Empire Strikes Back", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/434-star-wars-the-empire-strikes-back.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/434-star-wars-the-empire-strikes-back.jpg"],
    ["Starship Hector", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/435-starship-hector.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/435-starship-hector.jpg"],
    ["Street Fighter 2010 - The Final Fight", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/439-street-fighter-2010-the-final-fight.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/439-street-fighter-2010-the-final-fight.jpg"],
    ["Strider", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/440-strider.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/440-strider.jpg"],
    ["Super Pitfall", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/446-super-pitfall.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/446-super-pitfall.jpg"],
    ["Super Spike V Ball", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/447-super-spike-v-ball.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/447-super-spike-v-ball.jpg"],
    ["Super Turrican", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/450-super-turrican.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/450-super-turrican.jpg"],
    ["Superman", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/451-superman.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/451-superman.jpg"],
    ["Swamp Thing", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/452-swamp-thing.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/452-swamp-thing.jpg"],
    ["Sword Master", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/453-sword-master.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/453-sword-master.jpg"],
    ["TaleSpin", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/456-talespin.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/456-talespin.jpg"],
    ["Target - Renegade", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/457-target-renegade.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/457-target-renegade.jpg"],
    ["Teenage Mutant Ninja Turtles - Tournament Fighters", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/463-teenage-mutant-ninja-turtles-tournament-fighters.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/463-teenage-mutant-ninja-turtles-tournament-fighters.jpg"],
    ["Teenage Mutant Ninja Turtles III - The Manhattan Project", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/465-teenage-mutant-ninja-turtles-iii-the-manhattan-project.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/465-teenage-mutant-ninja-turtles-iii-the-manhattan-project.jpg"],
    ["Terminator 2 - Judgment Day", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/466-terminator-2-judgment-day.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/466-terminator-2-judgment-day.jpg"],
    ["Terminator", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/467-terminator.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/467-terminator.jpg"],
    ["Thunder & Lightning", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/471-thunder-lightning.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/471-thunder-lightning.jpg"],
    ["Tiger-Heli", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/474-tiger-heli.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/474-tiger-heli.jpg"],
    ["Time Lord", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/475-time-lord.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/475-time-lord.jpg"],
    ["Toki", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/481-toki.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/481-toki.jpg"],
    ["Totally Rad", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/486-totally-rad.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/486-totally-rad.jpg"],
    ["Track & Field", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/488-track-field.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/488-track-field.jpg"],
    ["Trojan", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/490-trojan.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/490-trojan.jpg"],
    ["Trolls in Crazyland", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/491-trolls-in-crazyland.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/491-trolls-in-crazyland.jpg"],
    ["Twin Eagle - Revenge Joe's Brother", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/493-twin-eagle-revenge-joe-s-brother.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/493-twin-eagle-revenge-joe-s-brother.jpg"],
    ["U-four-ia - The Saga", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/494-u-four-ia-the-saga.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/494-u-four-ia-the-saga.jpg"],
    ["Ultimate Air Combat", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/498-ultimate-air-combat.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/498-ultimate-air-combat.jpg"],
    ["Uncharted Waters", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/501-uncharted-waters.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/501-uncharted-waters.jpg"],
    ["Uninvited", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/502-uninvited.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/502-uninvited.jpg"],
    ["Vice - Project Doom", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/504-vice-project-doom.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/504-vice-project-doom.jpg"],
    ["Wacky Races", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/506-wacky-races.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/506-wacky-races.jpg"],
    ["Wayne's World", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/510-wayne-s-world.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/510-wayne-s-world.jpg"],
    ["Werewolf - The Last Warrior", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/512-werewolf-the-last-warrior.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/512-werewolf-the-last-warrior.jpg"],
    ["Whomp Em", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/518-whomp-em.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/518-whomp-em.jpg"],
    ["Wizardry - Proving Grounds of the Mad Overlord", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/521-wizardry-proving-grounds-of-the-mad-overlord.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/521-wizardry-proving-grounds-of-the-mad-overlord.jpg"],
    ["Wolverine", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/524-wolverine.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/524-wolverine.jpg"],
    ["2048", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/2048.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/2048.jpg"],
    // ["Xenophobe", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/532-xenophobe.nes", "//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/532-xenophobe.jpg"],
    // ["Xevious","//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/533-xevious.nes","//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/533-xevious.jpg"],
    // ["Yo  Noid","//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/535-yo-noid.nes","//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/535-yo-noid.jpg"],
    // ["Yoshi","//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/536-yoshi.nes","//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/536-yoshi.jpg"],
    // ["Yoshi's Cookie","//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/537-yoshi-s-cookie.nes","//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/537-yoshi-s-cookie.jpg"],
    // ["Young Indiana Jones Chronicles","//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/538-young-indiana-jones-chronicles.nes","//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/538-young-indiana-jones-chronicles.jpg"],
    // ["Zen - Intergalactic Ninja","//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/541-zen-intergalactic-ninja.nes","//cdn.jsdelivr.net/gh/omssp/nesscraper/roms/541-zen-intergalactic-ninja.jpg"]
];